import React from 'react';
import { useAppContext } from '../components/StateWarapper';
import Head from 'next/head';
import Menu from '../components/Menu';
import style from '../styles/Layout.module.css';
import Cart from '../components/Cart';
import Pay from './Pay';
const Layout = ({ children, title }) => {
  const content = useAppContext();
  return (
    <div className="relative">
      {content.pay && <Pay />}
      <Head>
        <title>Mandrilo store {title ? `| ${title}` : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div className={style.container}>{children}</div>
      <Cart />
    </div>
  );
};

export default Layout;
